name: Template API Note Writer

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  regular_run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      
      - name: Install the project
        run: cd template-api-note-writer && uv sync --locked 

      - name: Install xurl CLI
        run: |
          sudo bash -c "$(curl -fsSL https://raw.githubusercontent.com/xdevplatform/xurl/main/install.sh)"

      - name: Authenticate xurl via Oauth 1.0
        run: |
          echo "Authenticating xurl..."
          xurl auth oauth1 \
            --consumer-key "$X_API_KEY" \
            --consumer-secret "$X_API_KEY_SECRET" \
            --access-token "$X_ACCESS_TOKEN" \
            --token-secret "$X_ACCESS_TOKEN_SECRET"
        env: 
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_KEY_SECRET: ${{ secrets.X_API_KEY_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
      
      - name: Run bot with debug logging
        run: |
          set -x   # 打印每条命令
          cd template-api-note-writer
          # 捕获并打印 stdout / stderr
          uv run src/main.py > run_stdout.log 2> run_stderr.log || true
          echo "====== STDOUT ======"
          cat run_stdout.log
          echo "====== STDERR ======"
          cat run_stderr.log
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}  # 修正拼写错误（原来是 BERAER_TOKEN）
